[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["depthcrafter"]

[project]
name = "depthcrafter"
version = "1.0.1"
description = "Generating Consistent Long Depth Sequences for Open-world Videos"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "accelerate>=1.12.0",
    "decord>=0.6.0",
    "diffusers>=0.37.1",
    "fastapi==0.122.0",
    "fire>=0.7.1",
    "gradio==5.0.0",
    "huggingface-hub==0.36.2",
    "matplotlib>=3.10.7",
    "mediapy>=1.2.4",
    "pydantic==2.10.6",
    "pytest>=9.0.1",
    "spaces",
    "transformers==4.57.6",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu128"

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["unit_tests"]
